module Lexer.LexerSpec (spec) where

import Lexer.Common
import Test.Hspec (Spec, describe, it)
import Token (Token (..), TokenInfo (..))

spec :: Spec
spec = do
  describe "Lexer that runs on a real program" $ do
    it "should be able to lex real monkey program with all tokens" $ do
      let expected =
            [ TokenInfo {token = Let, startRow = 0, startCol = 0},
              TokenInfo {token = Identifier "add", startRow = 0, startCol = 4},
              TokenInfo {token = Assign, startRow = 0, startCol = 8},
              TokenInfo {token = Function, startRow = 0, startCol = 10},
              TokenInfo {token = LParen, startRow = 0, startCol = 12},
              TokenInfo {token = Identifier "a", startRow = 0, startCol = 13},
              TokenInfo {token = Comma, startRow = 0, startCol = 14},
              TokenInfo {token = Identifier "b", startRow = 0, startCol = 16},
              TokenInfo {token = RParen, startRow = 0, startCol = 17},
              TokenInfo {token = LBrace, startRow = 0, startCol = 18},
              TokenInfo {token = Return, startRow = 1, startCol = 2},
              TokenInfo {token = Identifier "a", startRow = 1, startCol = 9},
              TokenInfo {token = Plus, startRow = 1, startCol = 11},
              TokenInfo {token = Identifier "b", startRow = 1, startCol = 13},
              TokenInfo {token = Semicolon, startRow = 1, startCol = 14},
              TokenInfo {token = RBrace, startRow = 2, startCol = 0},
              TokenInfo {token = Let, startRow = 4, startCol = 0},
              TokenInfo {token = Identifier "main", startRow = 4, startCol = 4},
              TokenInfo {token = Assign, startRow = 4, startCol = 9},
              TokenInfo {token = Function, startRow = 4, startCol = 11},
              TokenInfo {token = LParen, startRow = 4, startCol = 13},
              TokenInfo {token = RParen, startRow = 4, startCol = 14},
              TokenInfo {token = LBrace, startRow = 4, startCol = 15},
              TokenInfo {token = Let, startRow = 5, startCol = 2},
              TokenInfo {token = Identifier "welcomeString", startRow = 5, startCol = 6},
              TokenInfo {token = Assign, startRow = 5, startCol = 20},
              TokenInfo {token = StringVal "\"Hello, \\\"Rishabh<rishabhdwivedi17@gmail.com>\\\"!\"", startRow = 5, startCol = 22},
              TokenInfo {token = Semicolon, startRow = 5, startCol = 71},
              TokenInfo {token = Let, startRow = 6, startCol = 2},
              TokenInfo {token = Identifier "regardsString", startRow = 6, startCol = 6},
              TokenInfo {token = Assign, startRow = 6, startCol = 20},
              TokenInfo {token = StringVal "\"Thanks,\n\n  Regards, Monkey\"", startRow = 6, startCol = 22},
              TokenInfo {token = Semicolon, startRow = 8, startCol = 18},
              TokenInfo {token = Let, startRow = 9, startCol = 2},
              TokenInfo {token = Identifier "x", startRow = 9, startCol = 6},
              TokenInfo {token = Assign, startRow = 9, startCol = 8},
              TokenInfo {token = Integer "1", startRow = 9, startCol = 10},
              TokenInfo {token = Plus, startRow = 9, startCol = 12},
              TokenInfo {token = Integer "2", startRow = 9, startCol = 14},
              TokenInfo {token = Minus, startRow = 9, startCol = 16},
              TokenInfo {token = Integer "3", startRow = 9, startCol = 18},
              TokenInfo {token = Asterisk, startRow = 9, startCol = 20},
              TokenInfo {token = Integer "4", startRow = 9, startCol = 22},
              TokenInfo {token = Slash, startRow = 9, startCol = 24},
              TokenInfo {token = Integer "5", startRow = 9, startCol = 26},
              TokenInfo {token = Mod, startRow = 9, startCol = 28},
              TokenInfo {token = Integer "6", startRow = 9, startCol = 30},
              TokenInfo {token = Illegal, startRow = 9, startCol = 32},
              TokenInfo {token = Integer "71", startRow = 9, startCol = 34},
              TokenInfo {token = BitOr, startRow = 9, startCol = 37},
              TokenInfo {token = Integer "8", startRow = 9, startCol = 39},
              TokenInfo {token = BitAnd, startRow = 9, startCol = 41},
              TokenInfo {token = Integer "9", startRow = 9, startCol = 43},
              TokenInfo {token = Semicolon, startRow = 9, startCol = 44},
              TokenInfo {token = Let, startRow = 10, startCol = 2},
              TokenInfo {token = Identifier "y", startRow = 10, startCol = 6},
              TokenInfo {token = Assign, startRow = 10, startCol = 8},
              TokenInfo {token = BitNegate, startRow = 10, startCol = 10},
              TokenInfo {token = Integer "10", startRow = 10, startCol = 11},
              TokenInfo {token = Semicolon, startRow = 10, startCol = 13},
              TokenInfo {token = Let, startRow = 11, startCol = 2},
              TokenInfo {token = Identifier "sum", startRow = 11, startCol = 6},
              TokenInfo {token = Assign, startRow = 11, startCol = 10},
              TokenInfo {token = Identifier "add", startRow = 11, startCol = 12},
              TokenInfo {token = LParen, startRow = 11, startCol = 15},
              TokenInfo {token = Identifier "x", startRow = 11, startCol = 16},
              TokenInfo {token = Comma, startRow = 11, startCol = 17},
              TokenInfo {token = Identifier "y", startRow = 11, startCol = 19},
              TokenInfo {token = RParen, startRow = 11, startCol = 20},
              TokenInfo {token = Semicolon, startRow = 11, startCol = 21},
              TokenInfo {token = Let, startRow = 12, startCol = 2},
              TokenInfo {token = Identifier "condition", startRow = 12, startCol = 6},
              TokenInfo {token = Assign, startRow = 12, startCol = 16},
              TokenInfo {token = Identifier "x", startRow = 12, startCol = 18},
              TokenInfo {token = Plus, startRow = 12, startCol = 20},
              TokenInfo {token = Identifier "y", startRow = 12, startCol = 22},
              TokenInfo {token = GreaterEq, startRow = 12, startCol = 24},
              TokenInfo {token = Identifier "sum", startRow = 12, startCol = 27},
              TokenInfo {token = Semicolon, startRow = 12, startCol = 30},
              TokenInfo {token = If, startRow = 13, startCol = 2},
              TokenInfo {token = LParen, startRow = 13, startCol = 4},
              TokenInfo {token = Identifier "condition", startRow = 13, startCol = 5},
              TokenInfo {token = RParen, startRow = 13, startCol = 14},
              TokenInfo {token = LBrace, startRow = 13, startCol = 15},
              TokenInfo {token = Identifier "print", startRow = 14, startCol = 4},
              TokenInfo {token = LParen, startRow = 14, startCol = 9},
              TokenInfo {token = StringVal "\"The condition was not \"", startRow = 14, startCol = 10},
              TokenInfo {token = Plus, startRow = 14, startCol = 35},
              TokenInfo {token = FalseVal, startRow = 14, startCol = 37},
              TokenInfo {token = RParen, startRow = 14, startCol = 42},
              TokenInfo {token = Semicolon, startRow = 14, startCol = 43},
              TokenInfo {token = RBrace, startRow = 15, startCol = 2},
              TokenInfo {token = Else, startRow = 15, startCol = 3},
              TokenInfo {token = LBrace, startRow = 15, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 16, startCol = 4},
              TokenInfo {token = LParen, startRow = 16, startCol = 9},
              TokenInfo {token = StringVal "\"The condition was not \"", startRow = 16, startCol = 10},
              TokenInfo {token = Plus, startRow = 16, startCol = 35},
              TokenInfo {token = TrueVal, startRow = 16, startCol = 37},
              TokenInfo {token = RParen, startRow = 16, startCol = 41},
              TokenInfo {token = Semicolon, startRow = 16, startCol = 42},
              TokenInfo {token = RBrace, startRow = 17, startCol = 2},
              TokenInfo {token = If, startRow = 19, startCol = 2},
              TokenInfo {token = LParen, startRow = 19, startCol = 4},
              TokenInfo {token = Integer "21", startRow = 19, startCol = 5},
              TokenInfo {token = Greater, startRow = 19, startCol = 8},
              TokenInfo {token = Integer "22", startRow = 19, startCol = 10},
              TokenInfo {token = RParen, startRow = 19, startCol = 12},
              TokenInfo {token = LBrace, startRow = 19, startCol = 13},
              TokenInfo {token = Identifier "print", startRow = 20, startCol = 4},
              TokenInfo {token = LParen, startRow = 20, startCol = 9},
              TokenInfo {token = StringVal "\"No way\"", startRow = 20, startCol = 10},
              TokenInfo {token = RParen, startRow = 20, startCol = 18},
              TokenInfo {token = Semicolon, startRow = 20, startCol = 19},
              TokenInfo {token = RBrace, startRow = 21, startCol = 2},
              TokenInfo {token = Else, startRow = 21, startCol = 3},
              TokenInfo {token = LBrace, startRow = 21, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 22, startCol = 4},
              TokenInfo {token = LParen, startRow = 22, startCol = 9},
              TokenInfo {token = StringVal "\"Good\"", startRow = 22, startCol = 10},
              TokenInfo {token = RParen, startRow = 22, startCol = 16},
              TokenInfo {token = Semicolon, startRow = 22, startCol = 17},
              TokenInfo {token = RBrace, startRow = 23, startCol = 2},
              TokenInfo {token = If, startRow = 24, startCol = 2},
              TokenInfo {token = LParen, startRow = 24, startCol = 4},
              TokenInfo {token = Integer "21", startRow = 24, startCol = 5},
              TokenInfo {token = Less, startRow = 24, startCol = 8},
              TokenInfo {token = Integer "22", startRow = 24, startCol = 10},
              TokenInfo {token = RParen, startRow = 24, startCol = 12},
              TokenInfo {token = LBrace, startRow = 24, startCol = 13},
              TokenInfo {token = Identifier "print", startRow = 25, startCol = 4},
              TokenInfo {token = LParen, startRow = 25, startCol = 9},
              TokenInfo {token = StringVal "\"Good\"", startRow = 25, startCol = 10},
              TokenInfo {token = RParen, startRow = 25, startCol = 16},
              TokenInfo {token = Semicolon, startRow = 25, startCol = 17},
              TokenInfo {token = RBrace, startRow = 26, startCol = 2},
              TokenInfo {token = Else, startRow = 26, startCol = 3},
              TokenInfo {token = LBrace, startRow = 26, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 27, startCol = 4},
              TokenInfo {token = LParen, startRow = 27, startCol = 9},
              TokenInfo {token = StringVal "\"No Way\"", startRow = 27, startCol = 10},
              TokenInfo {token = RParen, startRow = 27, startCol = 18},
              TokenInfo {token = Semicolon, startRow = 27, startCol = 19},
              TokenInfo {token = RBrace, startRow = 28, startCol = 2},
              TokenInfo {token = If, startRow = 29, startCol = 2},
              TokenInfo {token = LParen, startRow = 29, startCol = 4},
              TokenInfo {token = Integer "21", startRow = 29, startCol = 5},
              TokenInfo {token = LessEq, startRow = 29, startCol = 8},
              TokenInfo {token = Integer "22", startRow = 29, startCol = 11},
              TokenInfo {token = RParen, startRow = 29, startCol = 13},
              TokenInfo {token = LBrace, startRow = 29, startCol = 14},
              TokenInfo {token = Identifier "print", startRow = 30, startCol = 4},
              TokenInfo {token = LParen, startRow = 30, startCol = 9},
              TokenInfo {token = StringVal "\"Good\"", startRow = 30, startCol = 10},
              TokenInfo {token = RParen, startRow = 30, startCol = 16},
              TokenInfo {token = Semicolon, startRow = 30, startCol = 17},
              TokenInfo {token = RBrace, startRow = 31, startCol = 2},
              TokenInfo {token = Else, startRow = 31, startCol = 3},
              TokenInfo {token = LBrace, startRow = 31, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 32, startCol = 4},
              TokenInfo {token = LParen, startRow = 32, startCol = 9},
              TokenInfo {token = StringVal "\"No Way\"", startRow = 32, startCol = 10},
              TokenInfo {token = RParen, startRow = 32, startCol = 18},
              TokenInfo {token = Semicolon, startRow = 32, startCol = 19},
              TokenInfo {token = RBrace, startRow = 33, startCol = 2},
              TokenInfo {token = If, startRow = 34, startCol = 2},
              TokenInfo {token = LParen, startRow = 34, startCol = 4},
              TokenInfo {token = Integer "21", startRow = 34, startCol = 5},
              TokenInfo {token = GreaterEq, startRow = 34, startCol = 8},
              TokenInfo {token = Integer "22", startRow = 34, startCol = 11},
              TokenInfo {token = RParen, startRow = 34, startCol = 13},
              TokenInfo {token = LBrace, startRow = 34, startCol = 14},
              TokenInfo {token = Identifier "print", startRow = 35, startCol = 4},
              TokenInfo {token = LParen, startRow = 35, startCol = 9},
              TokenInfo {token = StringVal "\"No way\"", startRow = 35, startCol = 10},
              TokenInfo {token = RParen, startRow = 35, startCol = 18},
              TokenInfo {token = Semicolon, startRow = 35, startCol = 19},
              TokenInfo {token = RBrace, startRow = 36, startCol = 2},
              TokenInfo {token = Else, startRow = 36, startCol = 3},
              TokenInfo {token = LBrace, startRow = 36, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 37, startCol = 4},
              TokenInfo {token = LParen, startRow = 37, startCol = 9},
              TokenInfo {token = StringVal "\"Good\"", startRow = 37, startCol = 10},
              TokenInfo {token = RParen, startRow = 37, startCol = 16},
              TokenInfo {token = Semicolon, startRow = 37, startCol = 17},
              TokenInfo {token = RBrace, startRow = 38, startCol = 2},
              TokenInfo {token = If, startRow = 39, startCol = 2},
              TokenInfo {token = LParen, startRow = 39, startCol = 4},
              TokenInfo {token = Integer "21", startRow = 39, startCol = 5},
              TokenInfo {token = Equals, startRow = 39, startCol = 8},
              TokenInfo {token = Integer "22", startRow = 39, startCol = 11},
              TokenInfo {token = RParen, startRow = 39, startCol = 13},
              TokenInfo {token = LBrace, startRow = 39, startCol = 14},
              TokenInfo {token = Identifier "print", startRow = 40, startCol = 4},
              TokenInfo {token = LParen, startRow = 40, startCol = 9},
              TokenInfo {token = StringVal "\"No way\"", startRow = 40, startCol = 10},
              TokenInfo {token = RParen, startRow = 40, startCol = 18},
              TokenInfo {token = Semicolon, startRow = 40, startCol = 19},
              TokenInfo {token = RBrace, startRow = 41, startCol = 2},
              TokenInfo {token = Else, startRow = 41, startCol = 3},
              TokenInfo {token = LBrace, startRow = 41, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 42, startCol = 4},
              TokenInfo {token = LParen, startRow = 42, startCol = 9},
              TokenInfo {token = StringVal "\"Good\"", startRow = 42, startCol = 10},
              TokenInfo {token = RParen, startRow = 42, startCol = 16},
              TokenInfo {token = Semicolon, startRow = 42, startCol = 17},
              TokenInfo {token = RBrace, startRow = 43, startCol = 2},
              TokenInfo {token = If, startRow = 44, startCol = 2},
              TokenInfo {token = LParen, startRow = 44, startCol = 4},
              TokenInfo {token = Not, startRow = 44, startCol = 5},
              TokenInfo {token = LParen, startRow = 44, startCol = 6},
              TokenInfo {token = Integer "21", startRow = 44, startCol = 7},
              TokenInfo {token = Equals, startRow = 44, startCol = 10},
              TokenInfo {token = Integer "22", startRow = 44, startCol = 13},
              TokenInfo {token = And, startRow = 44, startCol = 16},
              TokenInfo {token = Integer "22", startRow = 44, startCol = 19},
              TokenInfo {token = Equals, startRow = 44, startCol = 22},
              TokenInfo {token = Integer "23", startRow = 44, startCol = 25},
              TokenInfo {token = Or, startRow = 44, startCol = 28},
              TokenInfo {token = Integer "24", startRow = 44, startCol = 31},
              TokenInfo {token = Equals, startRow = 44, startCol = 34},
              TokenInfo {token = Integer "24", startRow = 44, startCol = 37},
              TokenInfo {token = RParen, startRow = 44, startCol = 39},
              TokenInfo {token = RParen, startRow = 44, startCol = 40},
              TokenInfo {token = LBrace, startRow = 44, startCol = 41},
              TokenInfo {token = Identifier "print", startRow = 45, startCol = 4},
              TokenInfo {token = LParen, startRow = 45, startCol = 9},
              TokenInfo {token = StringVal "\"Don't know what is it\"", startRow = 45, startCol = 10},
              TokenInfo {token = RParen, startRow = 45, startCol = 33},
              TokenInfo {token = Semicolon, startRow = 45, startCol = 34},
              TokenInfo {token = RBrace, startRow = 46, startCol = 2},
              TokenInfo {token = Else, startRow = 46, startCol = 3},
              TokenInfo {token = LBrace, startRow = 46, startCol = 7},
              TokenInfo {token = Identifier "print", startRow = 47, startCol = 4},
              TokenInfo {token = LParen, startRow = 47, startCol = 9},
              TokenInfo {token = StringVal "\"Don't know\"", startRow = 47, startCol = 10},
              TokenInfo {token = RParen, startRow = 47, startCol = 22},
              TokenInfo {token = Semicolon, startRow = 47, startCol = 23},
              TokenInfo {token = RBrace, startRow = 48, startCol = 2},
              TokenInfo {token = RBrace, startRow = 49, startCol = 0}
            ]
      testFile "program.monkey" expected
