module Lexer.LexerSpec (spec) where

import Info (Info (Info), startCol, startRow, val)
import Lexer.Common (testFile)
import Test.Hspec (Spec, describe, it)
import Token (Token (..))

spec :: Spec
spec = do
  describe "Lexer that runs on a real program" $ do
    it "should be able to lex real monkey program with all tokens" $ do
      let expected =
            [ Info {val = Let, startRow = 0, startCol = 0},
              Info {val = Identifier "add", startRow = 0, startCol = 4},
              Info {val = Assign, startRow = 0, startCol = 8},
              Info {val = Function, startRow = 0, startCol = 10},
              Info {val = LParen, startRow = 0, startCol = 12},
              Info {val = Identifier "a", startRow = 0, startCol = 13},
              Info {val = Comma, startRow = 0, startCol = 14},
              Info {val = Identifier "b", startRow = 0, startCol = 16},
              Info {val = RParen, startRow = 0, startCol = 17},
              Info {val = LBrace, startRow = 0, startCol = 18},
              Info {val = Return, startRow = 1, startCol = 2},
              Info {val = Identifier "a", startRow = 1, startCol = 9},
              Info {val = Plus, startRow = 1, startCol = 11},
              Info {val = Identifier "b", startRow = 1, startCol = 13},
              Info {val = Semicolon, startRow = 1, startCol = 14},
              Info {val = RBrace, startRow = 2, startCol = 0},
              Info {val = Let, startRow = 4, startCol = 0},
              Info {val = Identifier "main", startRow = 4, startCol = 4},
              Info {val = Assign, startRow = 4, startCol = 9},
              Info {val = Function, startRow = 4, startCol = 11},
              Info {val = LParen, startRow = 4, startCol = 13},
              Info {val = RParen, startRow = 4, startCol = 14},
              Info {val = LBrace, startRow = 4, startCol = 15},
              Info {val = Let, startRow = 5, startCol = 2},
              Info {val = Identifier "welcomeString", startRow = 5, startCol = 6},
              Info {val = Assign, startRow = 5, startCol = 20},
              Info {val = StringVal "\"Hello, \\\"Rishabh<rishabhdwivedi17@gmail.com>\\\"!\"", startRow = 5, startCol = 22},
              Info {val = Semicolon, startRow = 5, startCol = 71},
              Info {val = Let, startRow = 6, startCol = 2},
              Info {val = Identifier "regardsString", startRow = 6, startCol = 6},
              Info {val = Assign, startRow = 6, startCol = 20},
              Info {val = StringVal "\"Thanks,\n\n  Regards, Monkey\"", startRow = 6, startCol = 22},
              Info {val = Semicolon, startRow = 8, startCol = 18},
              Info {val = Let, startRow = 9, startCol = 2},
              Info {val = Identifier "x", startRow = 9, startCol = 6},
              Info {val = Assign, startRow = 9, startCol = 8},
              Info {val = Integer "1", startRow = 9, startCol = 10},
              Info {val = Plus, startRow = 9, startCol = 12},
              Info {val = Integer "2", startRow = 9, startCol = 14},
              Info {val = Minus, startRow = 9, startCol = 16},
              Info {val = Integer "3", startRow = 9, startCol = 18},
              Info {val = Asterisk, startRow = 9, startCol = 20},
              Info {val = Integer "4", startRow = 9, startCol = 22},
              Info {val = Slash, startRow = 9, startCol = 24},
              Info {val = Integer "5", startRow = 9, startCol = 26},
              Info {val = Mod, startRow = 9, startCol = 28},
              Info {val = Integer "6", startRow = 9, startCol = 30},
              Info {val = Illegal, startRow = 9, startCol = 32},
              Info {val = Integer "71", startRow = 9, startCol = 34},
              Info {val = BitOr, startRow = 9, startCol = 37},
              Info {val = Integer "8", startRow = 9, startCol = 39},
              Info {val = BitAnd, startRow = 9, startCol = 41},
              Info {val = Integer "9", startRow = 9, startCol = 43},
              Info {val = Semicolon, startRow = 9, startCol = 44},
              Info {val = Let, startRow = 10, startCol = 2},
              Info {val = Identifier "y", startRow = 10, startCol = 6},
              Info {val = Assign, startRow = 10, startCol = 8},
              Info {val = BitNegate, startRow = 10, startCol = 10},
              Info {val = Integer "10", startRow = 10, startCol = 11},
              Info {val = Semicolon, startRow = 10, startCol = 13},
              Info {val = Let, startRow = 11, startCol = 2},
              Info {val = Identifier "sum", startRow = 11, startCol = 6},
              Info {val = Assign, startRow = 11, startCol = 10},
              Info {val = Identifier "add", startRow = 11, startCol = 12},
              Info {val = LParen, startRow = 11, startCol = 15},
              Info {val = Identifier "x", startRow = 11, startCol = 16},
              Info {val = Comma, startRow = 11, startCol = 17},
              Info {val = Identifier "y", startRow = 11, startCol = 19},
              Info {val = RParen, startRow = 11, startCol = 20},
              Info {val = Semicolon, startRow = 11, startCol = 21},
              Info {val = Let, startRow = 12, startCol = 2},
              Info {val = Identifier "condition", startRow = 12, startCol = 6},
              Info {val = Assign, startRow = 12, startCol = 16},
              Info {val = Identifier "x", startRow = 12, startCol = 18},
              Info {val = Plus, startRow = 12, startCol = 20},
              Info {val = Identifier "y", startRow = 12, startCol = 22},
              Info {val = GreaterEq, startRow = 12, startCol = 24},
              Info {val = Identifier "sum", startRow = 12, startCol = 27},
              Info {val = Semicolon, startRow = 12, startCol = 30},
              Info {val = If, startRow = 13, startCol = 2},
              Info {val = LParen, startRow = 13, startCol = 4},
              Info {val = Identifier "condition", startRow = 13, startCol = 5},
              Info {val = RParen, startRow = 13, startCol = 14},
              Info {val = LBrace, startRow = 13, startCol = 15},
              Info {val = Identifier "print", startRow = 14, startCol = 4},
              Info {val = LParen, startRow = 14, startCol = 9},
              Info {val = StringVal "\"The condition was not \"", startRow = 14, startCol = 10},
              Info {val = Plus, startRow = 14, startCol = 35},
              Info {val = FalseVal, startRow = 14, startCol = 37},
              Info {val = RParen, startRow = 14, startCol = 42},
              Info {val = Semicolon, startRow = 14, startCol = 43},
              Info {val = RBrace, startRow = 15, startCol = 2},
              Info {val = Else, startRow = 15, startCol = 3},
              Info {val = LBrace, startRow = 15, startCol = 7},
              Info {val = Identifier "print", startRow = 16, startCol = 4},
              Info {val = LParen, startRow = 16, startCol = 9},
              Info {val = StringVal "\"The condition was not \"", startRow = 16, startCol = 10},
              Info {val = Plus, startRow = 16, startCol = 35},
              Info {val = TrueVal, startRow = 16, startCol = 37},
              Info {val = RParen, startRow = 16, startCol = 41},
              Info {val = Semicolon, startRow = 16, startCol = 42},
              Info {val = RBrace, startRow = 17, startCol = 2},
              Info {val = If, startRow = 19, startCol = 2},
              Info {val = LParen, startRow = 19, startCol = 4},
              Info {val = Integer "21", startRow = 19, startCol = 5},
              Info {val = Greater, startRow = 19, startCol = 8},
              Info {val = Integer "22", startRow = 19, startCol = 10},
              Info {val = RParen, startRow = 19, startCol = 12},
              Info {val = LBrace, startRow = 19, startCol = 13},
              Info {val = Identifier "print", startRow = 20, startCol = 4},
              Info {val = LParen, startRow = 20, startCol = 9},
              Info {val = StringVal "\"No way\"", startRow = 20, startCol = 10},
              Info {val = RParen, startRow = 20, startCol = 18},
              Info {val = Semicolon, startRow = 20, startCol = 19},
              Info {val = RBrace, startRow = 21, startCol = 2},
              Info {val = Else, startRow = 21, startCol = 3},
              Info {val = LBrace, startRow = 21, startCol = 7},
              Info {val = Identifier "print", startRow = 22, startCol = 4},
              Info {val = LParen, startRow = 22, startCol = 9},
              Info {val = StringVal "\"Good\"", startRow = 22, startCol = 10},
              Info {val = RParen, startRow = 22, startCol = 16},
              Info {val = Semicolon, startRow = 22, startCol = 17},
              Info {val = RBrace, startRow = 23, startCol = 2},
              Info {val = If, startRow = 24, startCol = 2},
              Info {val = LParen, startRow = 24, startCol = 4},
              Info {val = Integer "21", startRow = 24, startCol = 5},
              Info {val = Less, startRow = 24, startCol = 8},
              Info {val = Integer "22", startRow = 24, startCol = 10},
              Info {val = RParen, startRow = 24, startCol = 12},
              Info {val = LBrace, startRow = 24, startCol = 13},
              Info {val = Identifier "print", startRow = 25, startCol = 4},
              Info {val = LParen, startRow = 25, startCol = 9},
              Info {val = StringVal "\"Good\"", startRow = 25, startCol = 10},
              Info {val = RParen, startRow = 25, startCol = 16},
              Info {val = Semicolon, startRow = 25, startCol = 17},
              Info {val = RBrace, startRow = 26, startCol = 2},
              Info {val = Else, startRow = 26, startCol = 3},
              Info {val = LBrace, startRow = 26, startCol = 7},
              Info {val = Identifier "print", startRow = 27, startCol = 4},
              Info {val = LParen, startRow = 27, startCol = 9},
              Info {val = StringVal "\"No Way\"", startRow = 27, startCol = 10},
              Info {val = RParen, startRow = 27, startCol = 18},
              Info {val = Semicolon, startRow = 27, startCol = 19},
              Info {val = RBrace, startRow = 28, startCol = 2},
              Info {val = If, startRow = 29, startCol = 2},
              Info {val = LParen, startRow = 29, startCol = 4},
              Info {val = Integer "21", startRow = 29, startCol = 5},
              Info {val = LessEq, startRow = 29, startCol = 8},
              Info {val = Integer "22", startRow = 29, startCol = 11},
              Info {val = RParen, startRow = 29, startCol = 13},
              Info {val = LBrace, startRow = 29, startCol = 14},
              Info {val = Identifier "print", startRow = 30, startCol = 4},
              Info {val = LParen, startRow = 30, startCol = 9},
              Info {val = StringVal "\"Good\"", startRow = 30, startCol = 10},
              Info {val = RParen, startRow = 30, startCol = 16},
              Info {val = Semicolon, startRow = 30, startCol = 17},
              Info {val = RBrace, startRow = 31, startCol = 2},
              Info {val = Else, startRow = 31, startCol = 3},
              Info {val = LBrace, startRow = 31, startCol = 7},
              Info {val = Identifier "print", startRow = 32, startCol = 4},
              Info {val = LParen, startRow = 32, startCol = 9},
              Info {val = StringVal "\"No Way\"", startRow = 32, startCol = 10},
              Info {val = RParen, startRow = 32, startCol = 18},
              Info {val = Semicolon, startRow = 32, startCol = 19},
              Info {val = RBrace, startRow = 33, startCol = 2},
              Info {val = If, startRow = 34, startCol = 2},
              Info {val = LParen, startRow = 34, startCol = 4},
              Info {val = Integer "21", startRow = 34, startCol = 5},
              Info {val = GreaterEq, startRow = 34, startCol = 8},
              Info {val = Integer "22", startRow = 34, startCol = 11},
              Info {val = RParen, startRow = 34, startCol = 13},
              Info {val = LBrace, startRow = 34, startCol = 14},
              Info {val = Identifier "print", startRow = 35, startCol = 4},
              Info {val = LParen, startRow = 35, startCol = 9},
              Info {val = StringVal "\"No way\"", startRow = 35, startCol = 10},
              Info {val = RParen, startRow = 35, startCol = 18},
              Info {val = Semicolon, startRow = 35, startCol = 19},
              Info {val = RBrace, startRow = 36, startCol = 2},
              Info {val = Else, startRow = 36, startCol = 3},
              Info {val = LBrace, startRow = 36, startCol = 7},
              Info {val = Identifier "print", startRow = 37, startCol = 4},
              Info {val = LParen, startRow = 37, startCol = 9},
              Info {val = StringVal "\"Good\"", startRow = 37, startCol = 10},
              Info {val = RParen, startRow = 37, startCol = 16},
              Info {val = Semicolon, startRow = 37, startCol = 17},
              Info {val = RBrace, startRow = 38, startCol = 2},
              Info {val = If, startRow = 39, startCol = 2},
              Info {val = LParen, startRow = 39, startCol = 4},
              Info {val = Integer "21", startRow = 39, startCol = 5},
              Info {val = Equals, startRow = 39, startCol = 8},
              Info {val = Integer "22", startRow = 39, startCol = 11},
              Info {val = RParen, startRow = 39, startCol = 13},
              Info {val = LBrace, startRow = 39, startCol = 14},
              Info {val = Identifier "print", startRow = 40, startCol = 4},
              Info {val = LParen, startRow = 40, startCol = 9},
              Info {val = StringVal "\"No way\"", startRow = 40, startCol = 10},
              Info {val = RParen, startRow = 40, startCol = 18},
              Info {val = Semicolon, startRow = 40, startCol = 19},
              Info {val = RBrace, startRow = 41, startCol = 2},
              Info {val = Else, startRow = 41, startCol = 3},
              Info {val = LBrace, startRow = 41, startCol = 7},
              Info {val = Identifier "print", startRow = 42, startCol = 4},
              Info {val = LParen, startRow = 42, startCol = 9},
              Info {val = StringVal "\"Good\"", startRow = 42, startCol = 10},
              Info {val = RParen, startRow = 42, startCol = 16},
              Info {val = Semicolon, startRow = 42, startCol = 17},
              Info {val = RBrace, startRow = 43, startCol = 2},
              Info {val = If, startRow = 44, startCol = 2},
              Info {val = LParen, startRow = 44, startCol = 4},
              Info {val = Not, startRow = 44, startCol = 5},
              Info {val = LParen, startRow = 44, startCol = 6},
              Info {val = Integer "21", startRow = 44, startCol = 7},
              Info {val = Equals, startRow = 44, startCol = 10},
              Info {val = Integer "22", startRow = 44, startCol = 13},
              Info {val = And, startRow = 44, startCol = 16},
              Info {val = Integer "22", startRow = 44, startCol = 19},
              Info {val = Equals, startRow = 44, startCol = 22},
              Info {val = Integer "23", startRow = 44, startCol = 25},
              Info {val = Or, startRow = 44, startCol = 28},
              Info {val = Integer "24", startRow = 44, startCol = 31},
              Info {val = Equals, startRow = 44, startCol = 34},
              Info {val = Integer "24", startRow = 44, startCol = 37},
              Info {val = RParen, startRow = 44, startCol = 39},
              Info {val = RParen, startRow = 44, startCol = 40},
              Info {val = LBrace, startRow = 44, startCol = 41},
              Info {val = Identifier "print", startRow = 45, startCol = 4},
              Info {val = LParen, startRow = 45, startCol = 9},
              Info {val = StringVal "\"Don't know what is it\"", startRow = 45, startCol = 10},
              Info {val = RParen, startRow = 45, startCol = 33},
              Info {val = Semicolon, startRow = 45, startCol = 34},
              Info {val = RBrace, startRow = 46, startCol = 2},
              Info {val = Else, startRow = 46, startCol = 3},
              Info {val = LBrace, startRow = 46, startCol = 7},
              Info {val = Identifier "print", startRow = 47, startCol = 4},
              Info {val = LParen, startRow = 47, startCol = 9},
              Info {val = StringVal "\"Don't know\"", startRow = 47, startCol = 10},
              Info {val = RParen, startRow = 47, startCol = 22},
              Info {val = Semicolon, startRow = 47, startCol = 23},
              Info {val = RBrace, startRow = 48, startCol = 2},
              Info {val = RBrace, startRow = 49, startCol = 0},
              Info {val = EOF, startRow = 50, startCol = 0}
            ]
      testFile "program.monkey" expected
